#!/bin/bash
export MARTe2_Components_DIR=/home/superuser/Projects/MARTe2-components
export MARTe2_DIR=/home/superuser/Projects/MARTe2-dev
export LD_LIBRARY_PATH=/home/superuser/Projects/MARTe2-dev/Build/x86-linux/Core